### ISSUE TITLE
2015.3 and later

### ISSUE THREAD

**Issue by tom21091** [Digilent/vivado-boards#1]
There are some problems with the board files where they don't configure IP blocks correctly. Work is being done to fix this

**Comment by sbobrowicz** [comment]
Yup, seems like Xilinx changed something about how the board files work in 2015.3, and now we can no longer get away with not having a presets file. Presets will have to be added to all "new" board files

**Comment by tom21091** [comment]
Presets have been added. Issue should be resolved
