### ISSUE TITLE
Zedboard LEDs not working

### ISSUE THREAD

**Issue by ARamsey118** [Digilent/vivado-boards#14]
The Zedboard LEDs do not work when using the board files on Vivado 2018.2. Following the instructions [here](https://www.xilinx.com/support/university/vivado/vivado-workshops/Vivado-adv-embedded-design-zynq.html), the LEDs do not change when the switches are flipped, as expected. Switching the board to the built in board files, which list Avnet as the distributor instead, everything functions just fine. 

I believe this is related to [these lines](https://github.com/Digilent/vivado-boards/blob/master/new/board_files/zedboard/1.3/board.xml#L50-L73), which set up the LEDs to be connected to tristates. They are not present in the Avnet board files.

**Comment by artvvb** [comment]
Resolved with https://github.com/Digilent/vivado-boards/commit/0100dd8652407e2595d4927521552cb2e9f1e61f
