### ISSUE TITLE
issues with ZYNQ7 Processing System

### ISSUE THREAD

**Issue by khaidz** [Digilent/vivado-boards#26]
when i add new IP...(ZYNQ7 Processing System) i receive  warning [BD 41-176] The physical port 'S_AXI_GP2_rd_socket' specified in the portmap, is not found on the block! 
I think this is what causes my code to fail.
Is it right? Please help me fix it. Thanks
(sorry because my english)

**Comment by salimullah1** [comment]
@khaidz I am facing a similar issue. What was your solution to the problem?
