### ISSUE TITLE
Zedboard PS_CLK frequency incorrect

### ISSUE THREAD

**Issue by elodg** [Digilent/vivado-boards#30]
https://github.com/Digilent/vivado-boards/blob/18d7d68c415e31afdcdcd56ad2d281dca1e51d6c/new/board_files/zedboard/1.3/preset.xml#L166

Correct frequency is 33.333333 MHz.

**Comment by artvvb** [comment]
A user on the forum reported that this affects the UART baud rate. It's fixed by e5f0728cd284d10080ae8eb03fc86e7b5eafcb72
The fix has been tested in hardware with a simple hello world project.
