### ISSUE TITLE
pynq-z1 board awareness in vivado

### ISSUE THREAD

**Issue by jge64** [Digilent/vivado-boards#6]
I can see the board listed under the list of board when start a new vivado project and select board (instead of part, like in UG871 v2016.4 
https://www.xilinx.com/support/documentation/sw_manuals/xilinx2016_4/ug871-vivado-high-level-synthesis-tutorial.pdf

page 222, specify vivado project details), after following the pynq-z1 documentaion (copy the board files to specified folder of vivado path); it works like other xilinx board (like ZC702 eval board).

But, the board is not listed in the drop down list as presets when I do config Zynq AP SOC ( as in the same UG, page 229, like zc702 listed). I did see the preset file in the same board def files (zipped), and even tried to load it (import xps settings).

Without doing it successfully, I can not even run a hello word demo which needs to use UART (aparently, the usb/UART is on the pynq-z1 board).

Any procedure to follow so I Can have the board listed in the drop-down list in the projectsettings and in the presets?
Thanks,

**Comment by elodg** [comment]
If the board flow is used, Run Block Automation on the PS has an option to load board preset for the Zynq. Which is exactly what importing preset is doing, but only for Xilinx boards.
